# Create a GitHub action to email a report from a file at 6 a.m. daily
name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to the cloud
      run: echo "Deploying the app"

    - name: Email report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL }}
        password: ${{ secrets.PASSWORD }}
        subject: 'Daily report'
        body: 'Here is the daily report.'
        to: '